baseURL = 'https://thoughts.mednoter.com/'
languageCode = 'en-us'
title = "Ryan's Thoughts"
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true


[pagination]
pagerSize = 20

[permalinks]
  posts = "/:slug/"

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Ryan Lyu"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Ryan Lyu's thoughts on software development"
keywords = "blog,developer,personal"
info = ["Ruby Engineer", "AWS", "Kubernetes", "Human Resources SaaS"]
avatarURL = "images/avatar.jpg"
#gravatar = "ryan.lyu@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/xiaoronglv/thoughts"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/xiaoronglv/"

# [[params.social]]
# name = "Gitlab"
# icon = "fa-brands fa-gitlab fa-2x"
# weight = 2
# url = "https://gitlab.com/xiaoronglv/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/ryan_lvory"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/xiaoronglv/"

# [[params.social]]
# name = "Medium"
# icon = "fa-brands fa-medium fa-2x"
# weight = 5
# url = "https://medium.com/@johndoe"

[[params.social]]
name = "Stackoverflow"
icon = "fa-brands fa-stack-overflow fa-2x"
weight = 6
url = "https://stackoverflow.com/users/5117552/ryan-lyu"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 7
url = "https://thoughts.mednoter.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Articles"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[[languages.en.menu.main]]
name = "中文博客"
weight = 10
url = "https://mednoter.com/"